[2024-12-21T17:59:09.157+0000] {processor.py:157} INFO - Started process (PID=607) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T17:59:09.159+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T17:59:09.165+0000] {logging_mixin.py:154} INFO - [2024-12-21T17:59:09.164+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T17:59:09.188+0000] {logging_mixin.py:154} INFO - [2024-12-21T17:59:09.186+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T17:59:09.189+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T17:59:09.235+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.084 seconds
[2024-12-21T17:59:39.870+0000] {processor.py:157} INFO - Started process (PID=662) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T17:59:39.872+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T17:59:39.876+0000] {logging_mixin.py:154} INFO - [2024-12-21T17:59:39.875+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T17:59:39.903+0000] {logging_mixin.py:154} INFO - [2024-12-21T17:59:39.901+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T17:59:39.905+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T17:59:39.948+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.086 seconds
[2024-12-21T18:00:10.977+0000] {processor.py:157} INFO - Started process (PID=720) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:00:10.979+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:00:10.983+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:00:10.983+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:00:11.029+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:00:11.028+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:00:11.031+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:00:11.065+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.093 seconds
[2024-12-21T18:00:41.412+0000] {processor.py:157} INFO - Started process (PID=779) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:00:41.415+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:00:41.420+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:00:41.419+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:00:41.469+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:00:41.468+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:00:41.471+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:00:41.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.109 seconds
[2024-12-21T18:01:12.231+0000] {processor.py:157} INFO - Started process (PID=836) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:01:12.233+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:01:12.238+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:01:12.237+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:01:12.275+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:01:12.274+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:01:12.276+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:01:12.317+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.092 seconds
[2024-12-21T18:01:42.428+0000] {processor.py:157} INFO - Started process (PID=893) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:01:42.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:01:42.436+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:01:42.435+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:01:42.488+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:01:42.487+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:01:42.490+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:01:42.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.113 seconds
[2024-12-21T18:02:12.832+0000] {processor.py:157} INFO - Started process (PID=948) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:02:12.835+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:02:12.839+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:02:12.838+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:02:12.876+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:02:12.874+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:02:12.878+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:02:12.915+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.088 seconds
[2024-12-21T18:02:43.832+0000] {processor.py:157} INFO - Started process (PID=1012) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:02:43.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:02:43.843+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:02:43.842+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:02:43.900+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:02:43.896+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:02:43.904+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:02:43.941+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.115 seconds
[2024-12-21T18:03:14.542+0000] {processor.py:157} INFO - Started process (PID=1069) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:03:14.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:03:14.551+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:03:14.550+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:03:14.565+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:03:14.564+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:03:14.566+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:03:14.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.056 seconds
[2024-12-21T18:03:44.938+0000] {processor.py:157} INFO - Started process (PID=1127) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:03:44.941+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:03:44.948+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:03:44.947+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:03:44.974+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:03:44.972+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:03:44.975+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:03:45.016+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.087 seconds
[2024-12-21T18:04:16.000+0000] {processor.py:157} INFO - Started process (PID=1184) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:04:16.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:04:16.006+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:04:16.006+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:04:16.028+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:04:16.027+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:04:16.029+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:04:16.058+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.062 seconds
[2024-12-21T18:04:46.378+0000] {processor.py:157} INFO - Started process (PID=1241) to work on /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:04:46.380+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/price-prediction-workflow.py for tasks to queue
[2024-12-21T18:04:46.386+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:04:46.386+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:04:46.434+0000] {logging_mixin.py:154} INFO - [2024-12-21T18:04:46.432+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/price-prediction-workflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/price-prediction-workflow.py", line 83
    mse = mean_squared_error(y_actual, y_predicted)
    ^
IndentationError: expected an indented block
[2024-12-21T18:04:46.436+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/price-prediction-workflow.py
[2024-12-21T18:04:46.484+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/price-prediction-workflow.py took 0.113 seconds
